name: 연습

on:
  push:
    branches: main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: 출력하기
              run: |
                echo 'github actions'
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo ${{ secrets.USE_NAME }}